### ISSUE TITLE
Removing babel-runtime from the bundle

### ISSUE THREAD

**Issue by casertap** [s-yadav/react-meta-tags#21]
I was about to consider react-meta-tags but it is including babel-runtime in my client bundle and this is pretty bad.
Why do you need babel runtime in your final bundler by the way?
I am pretty sure this is inserted because of some babel plugins that you use
``` "plugins": ["transform-runtime", "transform-class-properties", "transform-object-rest-spread"]```
Or the preset: `es-2015` I am not sure.

I do not have this issue with I use the preset: `env` instead of those plugins
```  "presets": ["react", "env", "stage-0"] ```

If you wanted to investigate this issue I recommend using the webpack-bundle-analyzer to check the bundle size and content.
Thanks

**Comment by casertap** [comment]
Have a look to my PR here please: https://github.com/s-yadav/react-meta-tags/pull/22

**Comment by casertap** [comment]
by the way, you also have some `console.log` in your code.

**Comment by s-yadav** [comment]
Mostly log got added on last release. Will remove that. 

Regarding runtime its coming from `transform-runtime` plugin. transform-runtime (or external helper) is required so that babel helper methods are not added on all files. 
The bundle is having the whole core-js because I have not done proper tree shake. 
While it will be not be the issue if your using this in the cjs form  and if you are doing tree shake (as the runtime are just added on dist files), but this issue has to be fixed.

Will fix this.
